# Generated by Django 6.0.3 on 2026-03-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signalement',
            new_name='core_signal_status_f5e838_idx',
            old_name='core_signal_status_3f9459_idx',
        ),
        migrations.RenameIndex(
            model_name='signalement',
            new_name='core_signal_lat_5e86fb_idx',
            old_name='core_signal_lat_7a7325_idx',
        ),
    ]
