# Generated by Django 6.0.3 on 2026-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_signalement_video'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ressourcesavoir',
            new_name='core_ressou_institu_2bfd52_idx',
            old_name='core_rs_inst_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='ressourcesavoir',
            new_name='core_ressou_contrib_e85005_idx',
            old_name='core_rs_contrib_idx',
        ),
        migrations.AlterField(
            model_name='signalement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='signalements/', verbose_name='image'),
        ),
    ]
