# Generated by Django 6.0.3 on 2026-03-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_core_rs_inst_cat_idx_core_ressou_institu_2bfd52_idx_and_more'),
        ('core', '0006_signalement_reporter_hash'),
    ]

    operations = [
    ]
