# Generated by Django 6.0.3 on 2026-03-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_merge_20260312_2222"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_hash", models.CharField(max_length=128, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=64)),
                ("points", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-points", "-updated_at"],
                "indexes": [
                    models.Index(fields=["-points"], name="core_citize_points_76f912_idx"),
                    models.Index(fields=["-updated_at"], name="core_citize_updated_30fded_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("follower_hash", models.CharField(db_index=True, max_length=128)),
                ("target_hash", models.CharField(db_index=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["target_hash", "created_at"], name="core_follow_target__a5a319_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_hash", models.CharField(db_index=True, max_length=128)),
                ("ally_hash", models.CharField(db_index=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ally_hash", "created_at"], name="core_friend_ally_ha_06f552_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReputationNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipient_hash", models.CharField(db_index=True, max_length=128)),
                ("actor_hash", models.CharField(blank=True, max_length=128)),
                ("message", models.CharField(max_length=220)),
                ("kind", models.CharField(choices=[("ALLY_ALERT", "Alerte allié"), ("FOLLOW_KNOWLEDGE", "Publication suivi"), ("REPUTATION", "Réputation")], max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient_hash", "created_at"], name="core_reputa_recipie_38073f_idx"),
                    models.Index(fields=["recipient_hash", "is_read"], name="core_reputa_recipie_d545ed_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(fields=("follower_hash", "target_hash"), name="unique_follow_relation"),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(fields=("user_hash", "ally_hash"), name="unique_friendship_direction"),
        ),
    ]
