# Generated by Django 6.0.3 on 2026-03-12 23:40

from django.db import migrations, models


def backfill_profile_rank(apps, schema_editor):
    CitizenProfile = apps.get_model("core", "CitizenProfile")
    for profile in CitizenProfile.objects.all():
        points = int(profile.points or 0)
        if points >= 1000:
            rank_title = "Sentinelle Or"
            milestone = 1000
        elif points >= 500:
            rank_title = "Éclaireur Argent"
            milestone = 500
        elif points >= 100:
            rank_title = "Citoyen Bronze"
            milestone = 100
        else:
            rank_title = "Citoyen Novice"
            milestone = 0
        profile.rank_title = rank_title
        profile.milestone_announced = milestone
        profile.celebration_pending = False
        profile.celebration_message = ""
        profile.save(
            update_fields=[
                "rank_title",
                "milestone_announced",
                "celebration_pending",
                "celebration_message",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_social_gamification"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizenprofile",
            name="celebration_message",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="celebration_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="milestone_announced",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="rank_title",
            field=models.CharField(default="Citoyen Novice", max_length=64),
        ),
        migrations.RunPython(backfill_profile_rank, migrations.RunPython.noop),
    ]
