# Generated by Django 6.0.3 on 2026-03-12 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_rank_and_ceremony'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=280)),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent'), ('INFO', 'Info')], default='INFO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('device_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='citizenprofile',
            new_name='core_citize_points_324a8a_idx',
            old_name='core_citize_points_76f912_idx',
        ),
        migrations.RenameIndex(
            model_name='citizenprofile',
            new_name='core_citize_updated_7222b9_idx',
            old_name='core_citize_updated_30fded_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='core_follow_target__22955e_idx',
            old_name='core_follow_target__a5a319_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='core_friend_ally_ha_fb8337_idx',
            old_name='core_friend_ally_ha_06f552_idx',
        ),
        migrations.RenameIndex(
            model_name='reputationnotification',
            new_name='core_reputa_recipie_b747f2_idx',
            old_name='core_reputa_recipie_38073f_idx',
        ),
        migrations.RenameIndex(
            model_name='reputationnotification',
            new_name='core_reputa_recipie_586f2c_idx',
            old_name='core_reputa_recipie_d545ed_idx',
        ),
        migrations.RenameIndex(
            model_name='signalement',
            new_name='core_signal_reporte_c0f598_idx',
            old_name='core_signal_reporter_idx',
        ),
        migrations.AddField(
            model_name='adminbroadcast',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
