# Generated by Django 6.0.3 on 2026-03-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_adminbroadcast_pushsubscription_and_more'),
        ('core', '0011_citizenprofile_owner'),
    ]

    operations = [
    ]
