# Generated by Django 6.0.3 on 2026-03-13 01:03

from django.db import migrations, models


def normalize_rank_titles(apps, schema_editor):
    CitizenProfile = apps.get_model("core", "CitizenProfile")
    for profile in CitizenProfile.objects.all():
        points = int(profile.points or 0)
        if points >= 501:
            rank = "Or"
        elif points >= 101:
            rank = "Argent"
        else:
            rank = "Bronze"
        profile.rank_title = rank
        profile.save(update_fields=["rank_title"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_merge_20260312_2304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizenprofile",
            name="rank_title",
            field=models.CharField(default="Bronze", max_length=64),
        ),
        migrations.RunPython(normalize_rank_titles, migrations.RunPython.noop),
    ]
