# Generated by Django 6.0.3 on 2026-03-12 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rank_bronze_argent_or'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='category',
            field=models.CharField(choices=[('ENERGIE', 'Energie'), ('EAU', 'Eau'), ('INFRA', 'Infrastructure'), ('FRAIS', 'Frais illegaux'), ('INSECURITE', 'Insecurite'), ('CONSTITUTION', 'Constitution'), ('POLITIQUE', 'Politique')], max_length=20),
        ),
        migrations.CreateModel(
            name='DebateOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_device_id', models.CharField(db_index=True, max_length=128)),
                ('pseudonym', models.CharField(blank=True, max_length=64)),
                ('opinion_side', models.CharField(choices=[('LEGAL', 'Arguments Legaux'), ('CHANGE', 'Arguments de Changement')], max_length=10)),
                ('text', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='debates/audio/', verbose_name='audio')),
                ('transcription', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debate_opinions', to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_opinions', to='core.signalement')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['signalement', 'opinion_side', 'created_at'], name='core_debate_signale_206c7d_idx')],
                'constraints': [models.UniqueConstraint(fields=('signalement', 'unique_device_id'), name='unique_debate_opinion_per_signalement_device')],
            },
        ),
    ]
