# Generated by Django 6.0.3 on 2026-03-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_signalement_category_debateopinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='signalements/audio/', verbose_name='audio'),
        ),
    ]
