# Generated by Django 6.0.3 on 2026-03-12 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_signalement_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_device_id', models.CharField(db_index=True, max_length=128)),
                ('format', models.CharField(choices=[('TEXT', 'Texte'), ('AUDIO', 'Audio')], max_length=8)),
                ('text', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='signalements/reactions/audio/', verbose_name='audio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.signalement')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['signalement', 'created_at'], name='core_signal_signale_156402_idx')],
            },
        ),
    ]
