# Generated by Django 6.0.3 on 2026-03-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_moderationflag'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='abusereport',
            new_name='core_abuser_target__3c30e2_idx',
            old_name='core_abuser_target__a23d16_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationflag',
            new_name='core_modera_target__d56269_idx',
            old_name='core_modera_target__d46837_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationflag',
            new_name='core_modera_device__1d3077_idx',
            old_name='core_modera_device__057af4_idx',
        ),
    ]
