# Generated by Django 6.0.3 on 2026-03-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_adminbroadcast_title'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='core_chatro_provinc_b77e29_idx',
            old_name='core_chatro_provinc_6b0b19_idx',
        ),
        migrations.RenameIndex(
            model_name='directmessage',
            new_name='core_direct_recipie_8b6ea5_idx',
            old_name='core_direct_recipie_dcc4d0_idx',
        ),
        migrations.RenameIndex(
            model_name='directmessage',
            new_name='core_direct_sender__5f9cff_idx',
            old_name='core_direct_sender__363377_idx',
        ),
        migrations.RenameIndex(
            model_name='neighborhoodchatmessage',
            new_name='core_neighb_room_ke_e89220_idx',
            old_name='core_neighb_room_ke_52b146_idx',
        ),
        migrations.RenameIndex(
            model_name='neighborhoodchatmessage',
            new_name='core_neighb_sender__441156_idx',
            old_name='core_neighb_sender__8bd634_idx',
        ),
        migrations.RenameIndex(
            model_name='signalementmoodreaction',
            new_name='core_signal_signale_a1accd_idx',
            old_name='core_signal_signale_3adf38_idx',
        ),
    ]
