# Generated by Codex on 2026-03-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_broadcastcomment_broadcastreaction"),
        ("core", "0031_rename_core_chatro_provinc_6b0b19_idx_core_chatro_provinc_b77e29_idx_and_more"),
    ]

    operations = []
