# Generated by Django 6.0.3 on 2026-03-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_ressourcecitation_ressourcemention'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='broadcastcomment',
            new_name='core_broadc_broadca_384ae9_idx',
            old_name='core_broadc_broadca_a24915_idx',
        ),
        migrations.RenameIndex(
            model_name='broadcastreaction',
            new_name='core_broadc_broadca_71b18b_idx',
            old_name='core_broadc_broadca_166210_idx',
        ),
    ]
