from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    RessourceSavoirViewSet,
    SignalementViewSet,
    admin_broadcast_latest_view,
    admin_broadcast_react_view,
    admin_broadcast_thread_view,
    admin_broadcast_view,
    admin_intervention_create_view,
    auth_view,
    command_hq_view,
    home_view,
    admin_control_view,
    latest_poll_signalement_view,
    logout_view,
    manifest_view,
    moderation_ban_user_view,
    moderation_delete_all_reports_view,
    moderation_warn_user_view,
    profile_view,
    profile_detail_view,
    push_public_key_view,
    push_subscribe_view,
    send_push_notification,
    self_profile_summary_view,
    social_ally_toggle_view,
    social_ally_request_view,
    social_direct_messages_view,
    social_follow_toggle_view,
    social_leaderboard_view,
    social_message_updates_view,
    social_neighborhood_messages_view,
    social_notifications_view,
    social_profile_view,
    service_worker_view,
    survey_response_view,
)

router = DefaultRouter()
router.register(r"signalements", SignalementViewSet, basename="signalements")
router.register(r"ressources", RessourceSavoirViewSet, basename="ressources")

urlpatterns = [
    path("", home_view, name="home"),
    path("auth/", auth_view, name="auth"),
    path("logout/", logout_view, name="logout"),
    path("profil/", profile_view, name="profile"),
    path("profile/<int:profile_id>/", profile_detail_view, name="profile-detail"),
    path("admin-control/", admin_control_view, name="admin-control"),
    path("admin-control/interventions/", admin_intervention_create_view, name="admin-intervention-create"),
    path("moderation/", admin_control_view, name="moderation"),
    path("moderation/warn/<int:profile_id>/", moderation_warn_user_view, name="moderation-warn-user"),
    path("moderation/ban/<int:user_id>/", moderation_ban_user_view, name="moderation-ban-user"),
    path("moderation/delete-all/<int:profile_id>/", moderation_delete_all_reports_view, name="moderation-delete-all"),
    path("admin-broadcast/", admin_broadcast_view, name="admin-broadcast"),
    path("command-hq/", command_hq_view, name="command-hq"),
    path("manifest.json", manifest_view, name="manifest"),
    path("sw.js", service_worker_view, name="sw"),
    path("api/push/public-key/", push_public_key_view, name="push-public-key"),
    path("api/push/subscribe/", push_subscribe_view, name="push-subscribe"),
    path("api/admin/send-push/", send_push_notification, name="send-push-notification"),
    path("api/admin-broadcast/latest/", admin_broadcast_latest_view, name="admin-broadcast-latest"),
    path("api/admin-broadcast/thread/", admin_broadcast_thread_view, name="admin-broadcast-thread"),
    path("api/admin-broadcast/react/", admin_broadcast_react_view, name="admin-broadcast-react"),
    path("api/signalements/latest-poll/", latest_poll_signalement_view, name="latest-poll-signalement"),
    path("api/survey/respond/", survey_response_view, name="survey-respond"),
    path("api/social/profile/", social_profile_view, name="social-profile"),
    path("api/profile/summary/", self_profile_summary_view, name="profile-summary"),
    path("api/social/follow/toggle/", social_follow_toggle_view, name="social-follow-toggle"),
    path("api/social/ally/toggle/", social_ally_toggle_view, name="social-ally-toggle"),
    path("api/social/ally/request/", social_ally_request_view, name="social-ally-request"),
    path("api/social/notifications/", social_notifications_view, name="social-notifications"),
    path("api/social/messages/direct/", social_direct_messages_view, name="social-direct-messages"),
    path("api/social/messages/room/", social_neighborhood_messages_view, name="social-neighborhood-messages"),
    path("api/social/messages/updates/", social_message_updates_view, name="social-message-updates"),
    path("api/social/leaderboard/", social_leaderboard_view, name="social-leaderboard"),
    path("api/", include(router.urls)),
]
